Imports System.IO
Imports System.Text

''' <summary>
''' SQL INSERT 文エクスポートロジック
'''
''' 2つのエクスポート経路を提供:
''' 1. C DLL 経由 (Workspace): DUMP ファイルを再パースしながらストリーミング出力
''' 2. VB.NET インメモリ (TablePreview): フィルタ後データを StreamWriter で逐次書き出し
'''
''' 対応 DBMS: Oracle, PostgreSQL, MySQL, SQL Server
''' </summary>
Public Class SqlExportLogic

    ''' <summary>
    ''' C DLL 経由で SQL エクスポート (全行・ストリーミング)
    ''' </summary>
    Public Shared Function ExportFromDump(ctx As ExportHelper.TableExportContext, outputPath As String, dbmsType As Integer) As Boolean
        Dim rc = OraDB_NativeParser.ExportSql(ctx.DumpFilePath, ctx.TableName, outputPath, dbmsType,
                                               ctx.Schema, ctx.DataOffset)
        If rc <> OraDB_NativeParser.ODV_OK Then
            Throw New Exception(Loc.SF("SqlExport_ErrorRc", rc))
        End If
        Return True
    End Function

    ''' <summary>
    ''' VB.NET インメモリデータから SQL INSERT 文を生成
    ''' BackgroundWorker から呼び出して進捗報告可能
    ''' </summary>
    Public Shared Function ExportFromData(data As List(Of String()),
                                          columnNames As List(Of String),
                                          columnTypes As String(),
                                          schema As String,
                                          tableName As String,
                                          outputPath As String,
                                          dbmsType As Integer,
                                          Optional worker As System.ComponentModel.BackgroundWorker = Nothing,
                                          Optional columnNotNulls As Boolean() = Nothing,
                                          Optional columnDefaults As String() = Nothing,
                                          Optional databaseName As String = Nothing) As Boolean
        Try
            Dim totalRows As Long = data.Count
            Dim isSqlServer = (dbmsType = ExportHelper.DBMS_SQLSERVER)

            ' SQL Server: スキーマを dbo に変換
            If isSqlServer AndAlso Not String.IsNullOrEmpty(schema) Then
                schema = "dbo"
            End If

            Using sw As New StreamWriter(outputPath, False, New UTF8Encoding(False))
                ' USE [DB] (SQL Server のみ、DB名が指定されている場合)
                If isSqlServer AndAlso Not String.IsNullOrEmpty(databaseName) Then
                    sw.WriteLine($"USE [{databaseName}]")
                    sw.WriteLine("GO")
                    sw.WriteLine()
                End If

                ' ヘッダコメント
                sw.WriteLine($"-- Table: {schema}.{tableName}")
                sw.WriteLine("-- Generated by OraDB DUMP Viewer")
                sw.WriteLine()

                ' 裸 NUMBER → INTEGER 推定 (オプション)
                Dim effectiveTypes = columnTypes
                If ExportOptions.SqlInferInteger AndAlso columnTypes IsNot Nothing Then
                    effectiveTypes = ExportHelper.InferIntegerTypes(columnTypes, data, columnDefaults)
                End If

                ' CREATE TABLE DDL (オプション)
                If ExportOptions.SqlCreateTable AndAlso effectiveTypes IsNot Nothing Then
                    ' DROP TABLE IF EXISTS
                    WriteDropTable(sw, schema, tableName, dbmsType)

                    WriteCreateTable(sw, schema, tableName, columnNames, effectiveTypes, dbmsType,
                                     columnNotNulls, columnDefaults)
                    sw.WriteLine()

                    ' GO (SQL Server のみ)
                    If isSqlServer Then
                        sw.WriteLine("GO")
                        sw.WriteLine()
                    End If
                End If

                ' INSERT INTO ... (...) VALUES ( プレフィックスをキャッシュ
                Dim prefix = BuildInsertPrefix(schema, tableName, columnNames, dbmsType)

                ' データ行 (1行ずつストリーミング書き出し)
                For rowIdx As Long = 0 To totalRows - 1
                    If worker IsNot Nothing AndAlso worker.CancellationPending Then
                        Return False
                    End If

                    Dim row = data(CInt(rowIdx))
                    sw.Write(prefix)

                    For colIdx As Integer = 0 To columnNames.Count - 1
                        If colIdx > 0 Then sw.Write(", ")

                        Dim value As String = Nothing
                        If colIdx < row.Length Then value = row(colIdx)

                        If String.IsNullOrEmpty(value) Then
                            sw.Write("NULL")
                        ElseIf ExportHelper.IsNumericValue(value) Then
                            sw.Write(value)
                        Else
                            sw.Write(ExportHelper.EscapeSqlString(value))
                        End If
                    Next

                    sw.WriteLine(");")

                    ' 進捗報告 (1000行ごと)
                    If worker IsNot Nothing AndAlso (rowIdx Mod 1000 = 0 OrElse rowIdx = totalRows - 1) Then
                        Dim pct As Integer = CInt(If(totalRows > 0, (rowIdx + 1) * 100 \ totalRows, 100))
                        worker.ReportProgress(pct,
                            New ExportProgressDialog.ProgressInfo($"{schema}.{tableName}", rowIdx + 1, totalRows))
                    End If
                Next

                ' GO (SQL Server のみ)
                If isSqlServer AndAlso totalRows > 0 Then
                    sw.WriteLine("GO")
                End If
            End Using

            Return True

        Catch ex As Exception
            Throw New Exception(Loc.SF("SqlExport_Error", ex.Message), ex)
        End Try
    End Function

    ''' <summary>
    ''' DROP TABLE IF EXISTS を出力
    ''' </summary>
    Private Shared Sub WriteDropTable(sw As StreamWriter, schema As String, tableName As String, dbmsType As Integer)
        Dim fullName As String
        If Not String.IsNullOrEmpty(schema) Then
            fullName = ExportHelper.EscapeSqlIdentifier(schema, dbmsType) & "." & ExportHelper.EscapeSqlIdentifier(tableName, dbmsType)
        Else
            fullName = ExportHelper.EscapeSqlIdentifier(tableName, dbmsType)
        End If

        Select Case dbmsType
            Case ExportHelper.DBMS_MYSQL
                sw.WriteLine($"DROP TABLE IF EXISTS {fullName};")
            Case ExportHelper.DBMS_SQLSERVER
                sw.WriteLine($"DROP TABLE IF EXISTS {fullName};")
                sw.WriteLine("GO")
            Case ExportHelper.DBMS_POSTGRES
                sw.WriteLine($"DROP TABLE IF EXISTS {fullName};")
            Case Else ' Oracle
                sw.WriteLine("BEGIN")
                sw.WriteLine($"    EXECUTE IMMEDIATE 'DROP TABLE {fullName.Replace("'", "''")}';")
                sw.WriteLine("EXCEPTION WHEN OTHERS THEN NULL;")
                sw.WriteLine("END;")
                sw.WriteLine("/")
        End Select
        sw.WriteLine()
    End Sub

    ''' <summary>
    ''' CREATE TABLE DDL を出力 (NOT NULL / DEFAULT 対応)
    ''' </summary>
    Private Shared Sub WriteCreateTable(sw As StreamWriter, schema As String, tableName As String,
                                         columnNames As List(Of String), columnTypes As String(),
                                         dbmsType As Integer,
                                         Optional columnNotNulls As Boolean() = Nothing,
                                         Optional columnDefaults As String() = Nothing)
        Dim sb As New StringBuilder("CREATE TABLE ")

        If Not String.IsNullOrEmpty(schema) Then
            sb.Append(ExportHelper.EscapeSqlIdentifier(schema, dbmsType))
            sb.Append("."c)
        End If
        sb.Append(ExportHelper.EscapeSqlIdentifier(tableName, dbmsType))
        sb.AppendLine(" (")

        For i As Integer = 0 To columnNames.Count - 1
            If i > 0 Then sb.AppendLine(",")
            sb.Append("    ")
            sb.Append(ExportHelper.EscapeSqlIdentifier(columnNames(i), dbmsType))
            sb.Append(" ")
            If i < columnTypes.Length Then
                sb.Append(ExportHelper.MapOracleType(columnTypes(i), dbmsType))
            Else
                sb.Append("VARCHAR(4000)")
            End If

            ' NOT NULL
            If columnNotNulls IsNot Nothing AndAlso i < columnNotNulls.Length AndAlso columnNotNulls(i) Then
                sb.Append(" NOT NULL")
            End If

            ' DEFAULT
            If columnDefaults IsNot Nothing AndAlso i < columnDefaults.Length AndAlso
               Not String.IsNullOrEmpty(columnDefaults(i)) Then
                sb.Append($" DEFAULT {columnDefaults(i)}")
            End If
        Next

        sb.AppendLine()

        ' ON [PRIMARY] (SQL Server のみ)
        If dbmsType = ExportHelper.DBMS_SQLSERVER Then
            sb.AppendLine(") ON [PRIMARY];")
        Else
            sb.AppendLine(");")
        End If

        sw.Write(sb.ToString())
    End Sub

    ''' <summary>
    ''' INSERT INTO "schema"."table" ("col1", "col2") VALUES ( プレフィックスを構築
    ''' </summary>
    Private Shared Function BuildInsertPrefix(schema As String, tableName As String,
                                               columnNames As List(Of String), dbmsType As Integer) As String
        Dim sb As New StringBuilder("INSERT INTO ")

        If Not String.IsNullOrEmpty(schema) Then
            sb.Append(ExportHelper.EscapeSqlIdentifier(schema, dbmsType))
            sb.Append("."c)
        End If
        sb.Append(ExportHelper.EscapeSqlIdentifier(tableName, dbmsType))

        sb.Append(" (")
        For i As Integer = 0 To columnNames.Count - 1
            If i > 0 Then sb.Append(", ")
            sb.Append(ExportHelper.EscapeSqlIdentifier(columnNames(i), dbmsType))
        Next
        sb.Append(") VALUES (")

        Return sb.ToString()
    End Function

End Class
